name: Send PR to update consumer

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      repository:
        type: string
        required: true
      script-location:
        type: string
        required: true
      post-process:
        type: string
        required: false
    secrets:
      GH_BOT_GITHUB_TOKEN:
        required: true
      GH_BOT_PGP_PRIVATE_KEY:
        required: true
      GH_BOT_PGP_PASSPHRASE:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GH_BOT_PGP_PRIVATE_KEY }}
          passphrase: ${{ secrets.GH_BOT_PGP_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_config_global: true

      - uses: actions/checkout@v4
        with:
          ref: dd/bot-user # Include the changes commmited in the previous job
          token: ${{ secrets.GH_BOT_GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          path: ${{ inputs.repository }}
          token: ${{ secrets.GH_BOT_GITHUB_TOKEN }}

      - name: Copy reference script
        run: cp reference/develocity-injection.init.gradle ${{ inputs.repository }}/${{ inputs.script-location }}

      - name: Post-process target repository
        if: ${{ inputs.post-process }}
        working-directory: ${{ inputs.repository }}
        run: ${{ inputs.post-process }}

      # If there are no changes, this action will not create a pull request
      - name: Create or update pull request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          path: ${{ inputs.repository }}
          committer:  Bot Githubaction <bot-githubaction@gradle.com>
          author: Bot Githubaction <bot-githubaction@gradle.com>
          token: ${{ secrets.GH_BOT_GITHUB_TOKEN }}
          branch: bot/develocity-injection-init-script-update
          delete-branch: true
          title: 'Update develocity-injection init script to ${{ inputs.version }}'
          body: |
            Updates the develocity-injection init script to the latest reference script content
            from https://github.com/gradle/develocity-ci-injection.
          commit-message: | 
            Update develocity-injection init script to ${{ inputs.version }}

            Updates the develocity-injection init script to the latest reference script content
            from https://github.com/gradle/develocity-ci-injection.

      - name: Include link to PR in Job Summary
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: |
            echo "Pull request: ${{ steps.create-pr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
