name: Gradle initScript release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate reference script with version
        run: ./gradlew promote -Pversion=${{ inputs.version }}
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[bot] Promote init-script as ${{ inputs.version }}'
          tagging_message: '${{ inputs.version }}'

  update-gradle-actions:
    needs: [update-reference]
    uses: ./.github/workflows/gradle-send-update-pr.yml
    with:
      version: ${{ inputs.version }}
      repository: 'gradle/actions'
      script-location: 'sources/src/resources/init-scripts/gradle-actions.inject-develocity.init.gradle'
    secrets: inherit

#  update-develocity-gitlab-templates:
#    needs: [update-reference]
#    uses: ./.github/workflows/gradle-send-update-pr.yml
#    with:
#      version: ${{ inputs.version }}
#      repository: 'gradle/develocity-gitlab-templates'
#      script-location: 'src/gradle/init-scripts/develocity-injection.init.gradle'
#      post-process: './build.sh'
#    secrets: inherit
#
#  update-jenkins-gradle-plugin:
#    needs: [update-reference]
#    uses: ./.github/workflows/gradle-send-update-pr.yml
#    with:
#      version: ${{ inputs.version }}
#      repository: 'jenkinsci/gradle-plugin'
#      script-location: 'src/main/resources/hudson/plugins/gradle/injection/init-script.gradle'
#    secrets: inherit
#
#  update-develocity-bamboo-plugin:
#    needs: [update-reference]
#    uses: ./.github/workflows/gradle-send-update-pr.yml
#    with:
#      version: ${{ inputs.version }}
#      repository: 'gradle/develocity-bamboo-plugin'
#      script-location: 'src/main/resources/develocity/gradle/develocity-init-script.gradle'
#      post-process: |
#        sed -i "s/def ENV_VAR_PREFIX = ''/def ENV_VAR_PREFIX = 'bamboo_'/" src/main/resources/develocity/gradle/develocity-init-script.gradle
#    secrets: inherit
#
#  update-develocity-teamcity-plugin:
#    needs: [update-reference]
#    uses: ./.github/workflows/gradle-send-update-pr.yml
#    with:
#      version: ${{ inputs.version }}
#      repository: 'bigdaz/teamcity-build-scan-plugin'
#      script-location: 'agent/src/main/resources/build-scan-init.gradle'
#    secrets: inherit
